In [2]:
# Import libraries

import os
import numpy as np

In [3]:
# Load file names

calib_folder = "CalibFiles"
folder_path = os.path.join(os.getcwd(), calib_folder)
files_in_folder = os.listdir(folder_path)

In [4]:
# Load files into categories

x_files, y_files, zx_files, zy_files = [], [], [], []

data_lists = [x_files, y_files, zx_files, zy_files]
filenames = ["xmatrix", "ymatrix", "zxmatrix", "zymatrix"]

file_conf = zip(data_lists, filenames)

In [5]:
# insert files into categories

for data, filename in file_conf:
    for file in files_in_folder:
        if file.startswith(filename):
            data.append(file)
    data.sort()

print(data_lists)

[['xmatrix1.txt', 'xmatrix10.txt', 'xmatrix2.txt', 'xmatrix3.txt', 'xmatrix4.txt', 'xmatrix5.txt', 'xmatrix6.txt', 'xmatrix7.txt', 'xmatrix8.txt', 'xmatrix9.txt'], ['ymatrix1.txt', 'ymatrix10.txt', 'ymatrix2.txt', 'ymatrix3.txt', 'ymatrix4.txt', 'ymatrix5.txt', 'ymatrix6.txt', 'ymatrix7.txt', 'ymatrix8.txt', 'ymatrix9.txt'], ['zxmatrix1.txt', 'zxmatrix10.txt', 'zxmatrix2.txt', 'zxmatrix3.txt', 'zxmatrix4.txt', 'zxmatrix5.txt', 'zxmatrix6.txt', 'zxmatrix7.txt', 'zxmatrix8.txt', 'zxmatrix9.txt'], ['zymatrix1.txt', 'zymatrix10.txt', 'zymatrix2.txt', 'zymatrix3.txt', 'zymatrix4.txt', 'zymatrix5.txt', 'zymatrix6.txt', 'zymatrix7.txt', 'zymatrix8.txt', 'zymatrix9.txt']]


In [65]:
# load data from files

x_data, y_data, zx_data, zy_data = np.empty(([0])), np.empty(([0])), np.empty(([0])), np.empty(([0]))

data = [x_data, y_data, zx_data, zy_data]

data_config = zip(data, data_lists)


for dat, datlist in data_config:
    print(dat)
    print(datlist)
    placeholder = np.empty(([0]))
    for name in datlist:
        print(name)
        placeholder = np.append(placeholder, np.array([1]))

    print(placeholder)
    dat = placeholder
    print(dat)
print(data)


""" for dat, datlist in data_config:
    print(dat.size)
    for i in range(len(datlist)):
        placeholder = np.loadtxt(os.path.join(calib_folder, datlist[i]), delimiter=",")
        placeholder = placeholder.flatten()
        dat = np.append(dat, placeholder, axis=0)
    print(dat.size)

print(dat.shape) """




[]
['xmatrix1.txt', 'xmatrix10.txt', 'xmatrix2.txt', 'xmatrix3.txt', 'xmatrix4.txt', 'xmatrix5.txt', 'xmatrix6.txt', 'xmatrix7.txt', 'xmatrix8.txt', 'xmatrix9.txt']
xmatrix1.txt
xmatrix10.txt
xmatrix2.txt
xmatrix3.txt
xmatrix4.txt
xmatrix5.txt
xmatrix6.txt
xmatrix7.txt
xmatrix8.txt
xmatrix9.txt
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[]
['ymatrix1.txt', 'ymatrix10.txt', 'ymatrix2.txt', 'ymatrix3.txt', 'ymatrix4.txt', 'ymatrix5.txt', 'ymatrix6.txt', 'ymatrix7.txt', 'ymatrix8.txt', 'ymatrix9.txt']
ymatrix1.txt
ymatrix10.txt
ymatrix2.txt
ymatrix3.txt
ymatrix4.txt
ymatrix5.txt
ymatrix6.txt
ymatrix7.txt
ymatrix8.txt
ymatrix9.txt
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[]
['zxmatrix1.txt', 'zxmatrix10.txt', 'zxmatrix2.txt', 'zxmatrix3.txt', 'zxmatrix4.txt', 'zxmatrix5.txt', 'zxmatrix6.txt', 'zxmatrix7.txt', 'zxmatrix8.txt', 'zxmatrix9.txt']
zxmatrix1.txt
zxmatrix10.txt
zxmatrix2.txt
zxmatrix3.txt
zxmatrix4.txt
zxmatrix5.txt
zxmatrix6.txt
zxmatr

' for dat, datlist in data_config:\n    print(dat.size)\n    for i in range(len(datlist)):\n        placeholder = np.loadtxt(os.path.join(calib_folder, datlist[i]), delimiter=",")\n        placeholder = placeholder.flatten()\n        dat = np.append(dat, placeholder, axis=0)\n    print(dat.size)\n\nprint(dat.shape) '