In [17]:
import numpy as np

# set up

# create example affine trafo in homogeneous coordinates
M = np.r_[np.random.normal(size=(3,4)),[[0,0,0,1]]]
n = 4 # or more
# create n points as the columns of s
# note that homogeneous coordinates have a "dummy" 1, not 0, as last element
s = np.r_[np.random.normal(size=(3,n)),np.ones((1,n))]
# apply trafo, transformed points are the columns of d
d = M@s

# solve

# solving is as simple as
M_rec,resid,rank,sing = np.linalg.lstsq(s.T,d.T)
M_rec = M_rec.T

# you may want to inspect resid (should be small),
# rank (should be 4) and sing (shouldn't spread too wide)

# check

np.allclose(M,M_rec)
# True
print(M)
print(s)
print(d)

[[ 0.19238908  0.107506   -0.02797344  1.0075596 ]
 [-0.48591545  0.87013586 -0.06533777 -0.30054063]
 [-0.25966232  0.04659522  0.11056322 -0.8756104 ]
 [ 0.          0.          0.          1.        ]]
[[-0.29753744 -0.30852467  0.45934266  0.63311599]
 [-0.52125784  0.17545602 -1.0058212  -0.75099381]
 [-0.52940496 -1.36634868  0.63742295 -0.5710629 ]
 [ 1.          1.          1.          1.        ]]
[[ 0.90908758  1.00528687  0.96996939  1.06460246]
 [-0.5749376   0.09132102 -1.44059122 -1.22433614]
 [-0.88117198 -0.93839066 -0.97127531 -1.13813804]
 [ 1.          1.          1.          1.        ]]


/tmp/ipykernel_107867/1889563403.py:17: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  M_rec,resid,rank,sing = np.linalg.lstsq(s.T,d.T)


In [25]:
q = np.r_[[[1, 2]], [[0, 0]], [[0, 0]], [[1, 1]]]
q_m = np.r_[[[0, 0]], [[0, 0]], [[0, 1]], [[1, 1]]]

m_rec, resid, rank, sing = np.linalg.lstsq(q_m.T, q.T)
m_rec = m_rec.T

test1 = m_rec @ q_m

print(q)

print(test1)

[[1 2]
 [0 0]
 [0 0]
 [1 1]]
[[1. 2.]
 [0. 0.]
 [0. 0.]
 [1. 1.]]


/tmp/ipykernel_107867/3305001822.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  m_rec, resid, rank, sing = np.linalg.lstsq(q_m.T, q.T)
